<?php
$title = 'Borrar álbum';
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    ¿Estás seguro que desea borrar
    "<?= $this->escapeHtml($album->title) ?>" de
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Si" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>